# Generated by Django 4.2.5 on 2023-09-15 20:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 9, 15, 20, 50, 24, 410591, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
