# Generated by Django 4.2.5 on 2023-09-15 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_manager', '0002_product_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='date',
            new_name='expiry_date',
        ),
    ]
